import { server } from './server';

server.listen(process.env.PORT || 8888);

/**
 * ! METTRE A jOUR ET TERMINER LES CONTROLLERS, ROUTERS ET SCHEMAS
 * ! FAIRE UN MIDDLEWARE POUR THROW UNE ERREUR SI L'USER EST PRIVATE OU NON
 * ! POUR LES AUTRES USERS SANS PERMISSIONS
 * ! FAIRE UN NOUVEAU ROUTER, SCHEMA ET CONTROLLER POUR LE SERVICE DES TAGS D'ANIMES
 * ! REMPLIR LA DATABASE DE DONNEE RANDOM AVEC TINY-SEEDER
 *
 * ! PLUS TARDS :
 * ! FAIRE UNE METHODE POUR RECUPERER UN ANIME RANDOM
 * ! FAIRE UNE PROP PRIVATE SUR LES ANIMES D'UNE PERSONNE
 */
